name: Publish Cottontail DB Docker Image
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    # Setup Buildx environment
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - id: docker-build
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Push Docker image.
    - id: docker-login
      name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push Docker image.
    - id: docker-push
      name: Push Docker Image to DockerHub
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: vitrivr/cottontaildb:latest,vitrivr/cottontaildb:${{ env.VERSION }}